--Q1. What is the total revenue generated by male vs. female customers?
select gender , sum(purchase_amount) as revenue
from customer
group by gender

--Q2. Which customers used a discount but still spent more than the average purchase amount? 
select customer_id, purchase_amount
from customer
where discount_applied='Yes' and purchase_amount>= (select AVG(purchase_amount)from customer)

-- Q3. Which are the top 5 products with the highest average review rating?
select item_purchased, round(AVG(review_rating::numeric),2) as "average review rating"
from customer 
group by item_purchased
order by avg(review_rating) desc
limit 5

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select shipping_type, round(avg(purchase_amount),2) as "average_purchase_amount"
from customer 
where shipping_type in ('Standard','Express')
group by shipping_type
order by average_purchase_amount desc

--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.

SELECT subscription_status,
 COUNT(customer_id) AS total_customer,
 ROUND(AVG(purchase_amount),2) as avg_spend,
 ROUND(SUM(purchase_amount),2) as total_revenue
 FROM customer
 group by subscription_status
 order by total_revenue, avg_spend desc

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?

SELECT item_purchased,
ROUND(100 * SUM( CASE WHEN discount_applied='Yes' then 1 else 0 end)/COUNT(*),2) AS discount_rate
FROM customer
group by item_purchased
order by discount_rate desc
limit 5 ;

--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
with customer_type as (
SELECT customer_id, previous_purchases,

CASE
 WHEN previous_purchases = 1 then 'New'
 WHEN previous_purchases between 2 and 10 then 'Returning'
 ELSE 'Loyal'
 END as customer_segment 
 FROM customer
)
select customer_segment , count(*) as "Number of customers"
from customer_type
group by customer_segment 

--Q8. What are the top 3 most purchased products within each category? 
WITH item_counts AS (
SELECT category,
item_purchased, COUNT(customer_id) as total_orders,
ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) desc)as item_rank
from customer
group by category, item_purchased
)
select item_rank, category,item_purchased, total_orders
from item_counts
where item_rank <=3

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status, COUNT (customer_id) as repeat_buyers
FROM customer
WHERE previous_purchases > 5
group by subscription_status

--Q10. What is the revenue contribution of each age group? 
select age_group, sum(purchase_amount) as revenue
from customer
group by age_group
order by revenue desc


